# Generated by Django 3.2.3 on 2021-05-29 17:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobID', models.UUIDField(primary_key=True, serialize=False)),
                ('organisation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('jobID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='qaam.job')),
                ('personnel', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('resources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
    ]
